[package]
name = "hacker_rank"
version = "0.1.0"
authors = ["ytnk531@gmail.com <ytnk531@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
